const letterLines = [{text:'Aku sayang kamu, lebih dari yang sering bisa aku ungkapkan.'},{text:'Aku tahu waktu dan tenagaku banyak habis untuk pekerjaan, sampai kamu kadang merasa sendirian.'},{text:'Aku sayang kamu.',emphasis:true},{text:'Percayalah, semua yang sedang aku perjuangkan ini aku lakukan untuk kita, agar suatu hari nanti kita bisa hidup bersama.'}];
const $ = selector => document.querySelector(selector);
const wait = duration => new Promise(resolve => setTimeout(resolve, duration));
function makeHeart(className, values){const heart=document.createElement('span');heart.className=className;Object.entries(values).forEach(([key,value])=>heart.style.setProperty(key,value));return heart;}
function createBurst(){const burst=$('#heart-burst');const palette=['#b91c35','#d96a7a','#efaab7','#fff0ed'];for(let index=0;index<9;index+=1){const angle=index/9*Math.PI*2;const distance=48+index%3*24;burst.appendChild(makeHeart('burst-heart',{'--size':`${7+index%3*3}px`,'--heart-color':palette[index%palette.length],'--duration':`${1.1+index%4*.18}s`,'--delay':`${.65+index%3*.08}s`,'--x':`${Math.cos(angle)*distance}px`,'--y':`${Math.sin(angle)*distance-25}px`}));}}
function createFloatingHearts(){const field=$('#floating-hearts');for(let index=0;index<10;index+=1){field.appendChild(makeHeart('floating-heart',{'--size':`${4+index%4*2}px`,'--opacity':`${.16+index%4*.08}`,'--duration':`${5+index%5}s`,'--delay':`${-index*.8}s`,left:`${7+index*11%88}%`,top:`${18+index*17%70}%`}));}}
async function typeText(element,text,speed=42){for(const character of text){element.textContent+=character;await wait(character==='.'?speed*7:speed);}}
async function revealLetter(){const greeting=$('#letter-greeting');const body=$('#letter-body');const signature=$('#letter-signature');await typeText(greeting,'Hi, kamu...',75);await wait(650);for(const line of letterLines){const paragraph=document.createElement('p');if(line.emphasis)paragraph.className='emphasis';body.appendChild(paragraph);await typeText(paragraph,line.text,line.emphasis?95:36);await wait(line.emphasis?900:550);}await typeText(signature,'dari seseorang yang serius tentang kamu',45);await wait(900);$('#question').hidden=false;$('#sticker-text').textContent='so...?';setupScrapbookReveal();}
function setupScrapbookReveal(){const revealItems=document.querySelectorAll('.reveal-on-scroll');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');if(entry.target.classList.contains('memory-sheet--rose'))$('#sticker-text').textContent='hai kamu ♡';if(entry.target.classList.contains('memory-sheet--lavender'))$('#sticker-text').textContent='aku nungguin kamu...';if(entry.target.classList.contains('memory-sheet--cream'))$('#sticker-text').textContent='so...?';}})},{threshold:.3});revealItems.forEach(item=>observer.observe(item));}
async function playMusic(){const music=$('#bgm');const label=$('#music-label');try{await music.play();$('#music-toggle').setAttribute('aria-pressed','true');label.textContent='Music on';}catch(error){label.textContent='Music';}}
async function openEnvelope(){const opening=$('#opening-scene');const letterStage=$('#letter-stage');const seal=$('#wax-seal');if(opening.classList.contains('is-opening'))return;playMusic();opening.classList.add('is-opening');seal.disabled=true;createBurst();$('#sticker-text').textContent='finally...';await wait(2300);opening.hidden=true;letterStage.hidden=false;createFloatingHearts();await wait(650);$('#sticker-text').textContent='hehe...';revealLetter();}
function setupMusic(){const music=$('#bgm');const toggle=$('#music-toggle');const label=$('#music-label');toggle.addEventListener('click',async()=>{if(music.paused){await playMusic();}else{music.pause();toggle.setAttribute('aria-pressed','false');label.textContent='Music';}});}
function celebrate(){const stage=$('#letter-stage');for(let index=0;index<28;index+=1){stage.appendChild(makeHeart('burst-heart',{'--size':`${7+index%5*3}px`,'--heart-color':index%2?'#b91c35':'#efaab7','--duration':`${1.4+index%5*.12}s`,'--delay':`${index%8*.04}s`,'--x':`${(index*47)%100-50}vw`,'--y':`${-20-(index*31)%70}vh`,left:`${45+index%9}%`,top:'55%'}));}$('#answer').hidden=false;$('#sticker-text').textContent='YAY!!! ♡';$('#sticker').classList.add('sticker--happy');const experience=$('#experience');experience.classList.add('is-transitioning');setTimeout(()=>{$('#letter-stage').hidden=true;$('#memory-page').hidden=false;window.scrollTo({top:0,behavior:'instant'});experience.classList.remove('is-transitioning');setupPhotoReveal();},1700);}
function moveLaterButton(){const button=$('#choice-later');const question=$('#question');const bounds=question.getBoundingClientRect();const buttonBounds=button.getBoundingClientRect();const yesBounds=$('#choice-yes').getBoundingClientRect();const padding=18;let left=padding,top=padding;for(let attempt=0;attempt<20;attempt+=1){left=padding+Math.random()*(window.innerWidth-buttonBounds.width-padding*2);top=padding+Math.random()*(window.innerHeight-buttonBounds.height-padding*2);const overlapsYes=left<yesBounds.right+12&&left+buttonBounds.width>yesBounds.left-12&&top<yesBounds.bottom+12&&top+buttonBounds.height>yesBounds.top-12;const overlapsQuestion=left<bounds.right+12&&left+buttonBounds.width>bounds.left-12&&top<bounds.bottom+12&&top+buttonBounds.height>bounds.top-12;if(!overlapsYes&&!overlapsQuestion)break;}button.classList.add('is-escaping');button.style.left=`${left}px`;button.style.top=`${top}px`;button.textContent=Math.random()>.7?'ehh...':'Pikir dulu';setTimeout(()=>{button.textContent='Pikir dulu';},900);}
function setupPhotoReveal(){const items=document.querySelectorAll('.reveal-photo');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-visible');}),{threshold:.18});items.forEach(item=>observer.observe(item));}
function setupPhotoLightbox(){const lightbox=$('#photo-lightbox');document.querySelectorAll('.photo-memory img').forEach(image=>image.addEventListener('click',()=>{lightbox.hidden=false;$('#lightbox-image').src=image.src;$('#lightbox-image').alt=image.alt;$('#lightbox-caption').textContent=image.parentElement.querySelector('figcaption').textContent;}));const close=()=>{lightbox.hidden=true;$('#lightbox-image').src='';};$('#lightbox-close').addEventListener('click',close);lightbox.addEventListener('click',event=>{if(event.target===lightbox)close();});document.addEventListener('keydown',event=>{if(event.key==='Escape')close();});}
document.addEventListener('DOMContentLoaded',()=>{$('#wax-seal').addEventListener('click',openEnvelope);$('#choice-yes').addEventListener('click',celebrate);const later=$('#choice-later');later.addEventListener('mouseenter',moveLaterButton);later.addEventListener('touchstart',event=>{event.preventDefault();moveLaterButton();},{passive:false});setupMusic();setupPhotoLightbox();});
